### PR TITLE
Iss9 authentication from file

### LINKED ISSUE #9: Load Configuration from File
We should load user configuration (OAuth tokens, etc) from a file. This file should be added to `.gitignore` if it is to exist within the local repo path. Note that `org.kohsuke.github-api` currently reads this file from `~/.github`. This is fine, but respecting the `${XDG_CONFIG_HOME}` spec for dotfile location sounds like a good idea.

### PR DESCRIPTION
**Pull request by gurnben**
Completed a basic object-oriented method of creating and authenticating.  The connection is established upon object creation and a method was added to check the connection!  It will pull credentials directly from "~/.github".  

Resolves #9

### CODE REVIEW

**Comment by edwardstm** [comment]
README should reflect the option of using an OAuth token instead of username and password.

**Comment by edwardstm** [comment]
Also needs tests.

**Comment by gurnben** [comment]
Our Readme now includes OAuth options and we now have tests for the constructor and checkConnection().  One thing to note: the tests require a valid configuration of the ~/.github file.  If this is not correct, the checkConnection test will fail.

**Comment by edwardstm** [comment]
Test `shouldHaveAValidConnection` fails for me, but code compiles. Most likely something is wrong with my dotfile configuration.

**Pull request merged**
